# Generated by Django 3.0.6 on 2021-02-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datosbanesco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_up', models.DateField(verbose_name='fecha de subida')),
                ('archivo', models.FileField(upload_to='banescofiles')),
            ],
        ),
    ]
